version: '3'
services:
  web:
    image: areberntsen/ikt206g24v06:latest # Using image from Docker Hub
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=assignment5;Username=hiphopgutt1;Password=hiphopgutt1;
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=assignment5
      - POSTGRES_USER=hiphopgutt1
      - POSTGRES_PASSWORD=hiphopgutt1
    volumes:
      - db_data:/var/lib/postgresql/data

  proxy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup --name watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  db_data:
  caddy_data:
  caddy_config:
